export const paths = {
  home: "/",
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verify: "/auth/verify",
    createPin: "/auth/create-pin",
    confirmPin: "/auth/confirm-pin",
  },
  dashboard: {
    home: "/dashboard",
    wallet: "/dashboard/wallet",
    calculator: "/dashboard/calculator",
    messages: "/dashboard/messages",
    notifications: "/dashboard/notifications",
    transactionHistory: "/dashboard/transactions",
    transactionDetail: "/dashboard/transactions", // + /[id]
    deposit: "/dashboard/deposit",
    withdrawal: "/dashboard/withdrawal",
    withdrawalContinue: "/dashboard/withdrawal/continue",
    withdrawalInfo: "/dashboard/withdrawal/info",
    withdrawalReceipt: "/dashboard/withdrawal/receipt",
    more: "/dashboard/more",
  },
  bills: {
    airtime: "/dashboard/bills/airtime",
    data: "/dashboard/bills/data",
    cable: "/dashboard/bills/cable",
    cableData: "/dashboard/bills/cable/data",
    electricity: "/dashboard/bills/electricity",
    electricityData: "/dashboard/bills/electricity/data",
    betting: "/dashboard/bills/betting",
    receipt: "/dashboard/bills/receipt",
  },
  giftcards: {
    sell: "/dashboard/giftcards/sell",
    sellData: "/dashboard/giftcards/sell/data",
    sellReceipt: "/dashboard/giftcards/sell/receipt",
    sellStatus: "/dashboard/giftcards/sell/status",
    buy: "/dashboard/giftcards/buy",
    buyData: "/dashboard/giftcards/buy/data",
  },
  crypto: {
    sell: "/dashboard/crypto/sell",
    sellData: "/dashboard/crypto/sell/data",
    deposit: "/dashboard/crypto/deposit",
  },
  settings: {
    base: "/dashboard/settings",
    account: "/dashboard/settings/account",
    security: "/dashboard/settings/security",
    changePassword: "/dashboard/settings/change-password",
    changePin: "/dashboard/settings/change-pin",
    newPin: "/dashboard/settings/new-pin",
    banks: "/dashboard/settings/banks",
    addBank: "/dashboard/settings/banks/add",
    kyc: "/dashboard/settings/kyc",
    kycSuccess: "/dashboard/settings/kyc/success",
    ninVerification: "/dashboard/settings/kyc/nin",
    theme: "/dashboard/settings/theme",
    support: "/dashboard/settings/support",
    referrals: "/dashboard/settings/referrals",
    rank: "/dashboard/settings/rank",
    verificationCode: "/dashboard/settings/verification-code",
  },
} as const;
